#!/bin/bash

wallpaper_dir="$HOME/Obrazy/tapety/"

conf_dir="$HOME/.config/"
wal_dir="$HOME/.cache/wal/"
hypr_dir="$conf_dir/hypr"
waybar_dir="$conf_dir/waybar"

function restart_hyprpaper() {
  if pgrep hyprpaper >/dev/null; then
    killall hyprpaper
  fi
  nohup hyprpaper >/dev/null 2>&1 &
}

function restart_waybar() {
  if pgrep waybar >/dev/null; then
    killall waybar
  fi
  nohup waybar >/dev/null 2>&1 &
}

hex_to_rgba() {
  hex=$(echo $1 | sed 's/#//')
  r=${hex:0:2}
  g=${hex:2:2}
  b=${hex:4:2}

  if [[ ${#hex} -eq 8 ]]; then
    a=${hex:6:2}
  else
    a="ff"
  fi

  echo "rgba($r$g$b$a)"
}

get_color_in_rgba() {
  path="$wal_dir/colors"
  line_number=$1

  if [ ! -f "$path" ]; then
    echo "Plik nie istnieje!"
    return 1
  fi

  color=$(sed "${line_number}q;d" "$path")

  if [[ $color =~ ^#[0-9A-Fa-f]{6}$ ]]; then
    hex_to_rgba "$color"
  else
    echo "Nieprawidłowy kolor HEX w linii $line_number"
    return 1
  fi
}

choosen_wallpaper=$(find $wallpaper_dir -type f | rofi -dmenu -i -p "Wybierz tapetę")

if [[ -z $choosen_wallpaper]];then
  echo "Proszę wybrać tapetę"
  exit 1
fi

hyprpaper_content="
preload = $choosen_wallpaper\n
wallpaper = ,$choosen_wallpaper\n
splash = off\n
ipc = off
"

hyprlock_content="
background {\n
    monitor =\n
    path = $choosen_wallpaper\n
    color = rgba(25, 20, 20, 1.0)\n
\n
    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations\n
    blur_passes = 0 # 0 disables blurring\n
    blur_size = 7\n
    noise = 0.0117\n
    contrast = 0.8916\n
    brightness = 0.8172\n
    vibrancy = 0.1696\n
    vibrancy_darkness = 0.0\n
}\n
\n
input-field {\n
    monitor =\n
    size = 200, 50\n
    outline_thickness = 3\n
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8\n
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0\n
    dots_center = false\n
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding\n
    outer_color = rgb(151515)\n
    inner_color = rgb(200, 200, 200)\n
    font_color = rgb(10, 10, 10)\n
    fade_on_empty = true\n
    fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.\n
    placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.\n
    hide_input = false\n
    rounding = -1 # -1 means complete rounding (circle/oval)\n
    check_color = rgb(204, 136, 34)\n
    fail_color = rgb(204, 34, 34) # if authentication failed, changes outer_color and fail message color\n
    fail_text = <i>\$FAIL <b>(\$ATTEMPTS)</b></i> # can be set to empty\n
    fail_timeout = 2000 # milliseconds before fail_text and fail_color disappears\n
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color\n
    capslock_color = -1\n
    numlock_color = -1\n
    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)\n
    invert_numlock = false # change color if numlock is off\n
    swap_font_color = false # see below\n
\n
    position = 0, -20\n
    halign = center\n
    valign = center\n
}\n
\n 
label {\n
    monitor =\n
    text = Godzina \$TIME\n
    text_align = center\n
    color = $(get_color_in_rgba 12)\n
    font_size = 25\n
    font_family = Noto Sans\n
    rotate = 0 # degrees, counter-clockwise\n
\n
    position = 0, 80\n
    halign = center\n
    valign = center\n
    shadow_passes = 1\n
    shadow_color = $(get_color_in_rgba 8)
}\n
"

echo -e $hyprpaper_content >$hypr_dir/hyprpaper.conf
wal -i $choosen_wallpaper

color1=$(get_color_in_rgba 6)
color2=$(get_color_in_rgba 16)

hyprland_border="
# generated by wallpaper script\n
general {\n
   \tgaps_in = 5\n
   \tgaps_out = 14\n
   \tborder_size = 3\n
   \tcol.active_border =  $color1 $color2 45deg\n
   \tcol.inactive_border = rgba(595959aa)\n
   \tlayout = dwindle\n
   \tallow_tearing = false\n
}
"
color1="$(awk 'NR==5' $wal_dir/colors)"
color2="$(awk 'NR==11' $wal_dir/colors)"

vesktop_config="
@import url('https://devevil99.github.io/devevil/BetterDiscordAddons/Theme/Dark+/Dark+.theme.css');\n
:root {\n
  --darkplus-bg: #212121;\n
  --darkplus-bg2: #302f2f;\n
  --darkplus-sec: $color1;\n
  --darkplus-links: $color2;\n
  --darkplus-home-icon: url(https://i.imgur.com/btMrRiE.png);\n
  --watermark-filter-invert: 0%;\n
  --watermark-filter-sepia: 50%;\n
  --watermark-filter-saturate: 3000%;\n
  --watermark-filter-hue-rotate: 210deg;\n
  --watermark-filter-brightness: 70%;\n
  --watermark-filter-contrast: 200%;\n
}\n
"

border_color="$(awk 'NR==6' $wal_dir/colors)"

mako_config="
# Mako Configuration File\n
\n
# Notification sound\n
on-notify=exec paplay /usr/share/sounds/freedesktop/stereo/dialog-information.oga\n
\n
# Font settings\n
font=monospace\n
\n
# Colors\n
background-color=#2C2C2C\n
border-color=$border_color\n
\n
# Position and padding\n
margin=15\n
padding=15\n
\n
# Border settings\n
border-size=2\n
border-radius=20\n
\n
# size\n
width=400\n
height=400\n
\n
# Timeout settings\n
default-timeout=8000\n
"

cp "$wal_dir/colors-waybar.css" "$waybar_dir/style/var.css"
cp "$wal_dir/colors-kitty.conf" "$conf_dir/kitty/colors.conf"
cp "$wal_dir/colors-rofi-light.rasi" "$conf_dir/rofi/colors.rasi"
echo -e $hyprland_border >"$hypr_dir/files/general.conf"
echo -e $vesktop_config >"$conf_dir/vesktop/themes/Dark+.theme.css"
echo -e $mako_config | sed 's/^[[:space:]]*//' >"$conf_dir/mako/config"
echo -e $hyprlock_content | sed 's/^[[:space:]]*//' >"$hypr_dir/hyprlock.conf"

restart_hyprpaper
restart_waybar
makoctl reload
hyprctl reload
