#!/bin/bash

wallpaper_dir="$HOME/Obrazy/tapety/"

conf_dir="$HOME/.config/"
wal_dir="$HOME/.cache/wal/"
hypr_dir="$conf_dir/hypr"
waybar_dir="$conf_dir/waybar"

function restart_hyprpaper() {
  if pgrep hyprpaper >/dev/null; then
    killall hyprpaper
  fi
  nohup hyprpaper >/dev/null 2>&1 &
}

function restart_waybar() {
  if pgrep waybar >/dev/null; then
    killall waybar
  fi
  nohup waybar >/dev/null 2>&1 &
}

hex_to_rgba() {
  hex=$(echo $1 | sed 's/#//')
  r=${hex:0:2}
  g=${hex:2:2}
  b=${hex:4:2}

  if [[ ${#hex} -eq 8 ]]; then
    a=${hex:6:2}
  else
    a="ff"
  fi

  echo "rgba($r$g$b$a)"
}

get_color_in_rgba() {
  path="$wal_dir/colors"
  line_number=$1

  if [ ! -f "$path" ]; then
    echo "Plik nie istnieje!"
    return 1
  fi

  color=$(sed "${line_number}q;d" "$path")

  if [[ $color =~ ^#[0-9A-Fa-f]{6}$ ]]; then
    hex_to_rgba "$color"
  else
    echo "Nieprawidłowy kolor HEX w linii $line_number"
    return 1
  fi
}

choosen_wallpaper=$(find $wallpaper_dir -type f | rofi -dmenu -i -p "Wybierz tapetę")

hyprpaper_content="
preload = $choosen_wallpaper\n
wallpaper = ,$choosen_wallpaper\n
splash = off\n
ipc = off
"

echo -e $hyprpaper_content >$hypr_dir/hyprpaper.conf
wal -i $choosen_wallpaper

color1=$(get_color_in_rgba 6)
color2=$(get_color_in_rgba 16)

hyprland_border="
# generated by wallpaper script\n
general {\n
   \tgaps_in = 5\n
   \tgaps_out = 14\n
   \tborder_size = 3\n
   \tcol.active_border =  $color1 $color2 45deg\n
   \tcol.inactive_border = rgba(595959aa)\n
   \tlayout = dwindle\n
   \tallow_tearing = false\n
}
"
color1="$(awk 'NR==5' $wal_dir/colors)"
color2="$(awk 'NR==11' $wal_dir/colors)"

vesktop_config="
@import url('https://devevil99.github.io/devevil/BetterDiscordAddons/Theme/Dark+/Dark+.theme.css');\n
:root {\n
  --darkplus-bg: #212121;\n
  --darkplus-bg2: #302f2f;\n
  --darkplus-sec: $color1;\n
  --darkplus-links: $color2;\n
  --darkplus-home-icon: url(https://i.imgur.com/V2mA9Ns.png);\n
  --watermark-filter-invert: 0%;\n
  --watermark-filter-sepia: 50%;\n
  --watermark-filter-saturate: 3000%;\n
  --watermark-filter-hue-rotate: 210deg;\n
  --watermark-filter-brightness: 70%;\n
  --watermark-filter-contrast: 200%;\n
}\n
"

border_color="$(awk 'NR==6' $wal_dir/colors)"

mako_config="
# Mako Configuration File\n
\n
# Notification sound\n
on-notify=exec paplay /usr/share/sounds/freedesktop/stereo/dialog-information.oga\n
\n
# Font settings\n
font=monospace\n
\n
# Colors\n
background-color=#2C2C2C\n
border-color=$border_color\n
\n
# Position and padding\n
margin=15\n
padding=15\n
\n
# Border settings\n
border-size=2\n
border-radius=20\n
\n
# size\n
width=400\n
height=400\n
\n
# Timeout settings\n
default-timeout=8000\n
"

cp "$wal_dir/colors-waybar.css" "$waybar_dir/style/var.css"
cp "$wal_dir/colors-kitty.conf" "$conf_dir/kitty/colors.conf"
cp "$wal_dir/colors-rofi-light.rasi" "$conf_dir/rofi/colors.rasi"
echo -e $hyprland_border >"$hypr_dir/files/general.conf"
echo -e $vesktop_config >"$conf_dir/vesktop/themes/Dark+.theme.css"
echo -e $mako_config | sed 's/^[[:space:]]*//' >"$conf_dir/mako/config"

restart_hyprpaper
restart_waybar
makoctl reload
hyprctl reload
